### ISSUE TITLE
ToDo List (July 8)

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [kayhan-batmanghelich/drugEmbedding#6]
# Writing
- [x] Outline of the method section by Wed
- [ ] **Follow the 30-min per day guideline**
 
# Coding
- [ ] Explore the idea regularizing of the marginal posterior 
- [x] Explore the distance to mean of the latent variable from the center
- [ ] Try All-SMILES encoder
- [ ] Apply hierarchical clustering on the drug embedding space
- [x] Contact the authors of the All-SMILES paper to see if we can get their large-scale dataset
- [ ] Play with the slope of embedding of the annealing param $\beta$
